<a href="https://colab.research.google.com/github/VishalDalwadi/027_VishalDalwadi/blob/main/Lab4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

In [3]:
digits = datasets.load_digits()
print(digits)

print(digits.data.shape)
print(digits.target.shape)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0

In [6]:
from sklearn.model_selection import train_test_split

X=digits.data
Y=digits.target

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20, random_state = 27)

In [8]:
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 27, max_depth=7, min_samples_leaf=27)

clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=7, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=27, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=27, splitter='best')

In [11]:
y_pred = clf_gini.predict(X_test)
print("Predicted values:", y_pred)

Predicted values: [4 2 1 2 0 9 4 9 9 9 1 4 9 9 1 4 5 0 6 5 9 3 7 3 9 8 6 4 0 7 9 7 3 8 1 3 1
 9 6 8 0 3 2 2 0 0 5 7 5 0 0 5 9 0 4 2 6 3 5 4 6 5 9 1 9 7 9 9 3 6 6 7 2 4
 2 3 7 5 3 7 3 8 4 5 5 7 4 8 4 5 3 5 4 2 5 1 2 3 5 0 5 7 5 3 1 6 6 3 4 6 0
 8 4 1 4 6 1 0 5 1 5 6 1 4 1 1 4 2 4 2 6 0 3 8 5 5 9 9 4 3 6 2 5 8 2 1 5 4
 2 8 3 5 6 3 9 5 6 9 0 4 9 9 5 2 4 0 2 6 4 2 2 0 3 2 5 2 2 0 2 9 0 4 2 0 4
 5 4 9 7 6 4 2 8 5 6 4 5 7 0 0 0 5 5 4 4 9 8 1 3 9 5 8 0 3 4 1 3 5 2 3 4 1
 3 6 6 6 9 3 3 6 0 0 0 4 7 6 8 4 6 8 2 7 7 9 2 2 5 9 3 0 3 0 8 6 7 5 3 4 1
 3 8 8 4 2 2 9 1 8 8 5 9 6 4 3 3 4 1 5 0 3 3 0 5 2 5 8 6 3 9 9 7 9 5 3 1 5
 7 0 5 2 3 4 6 2 3 1 0 4 3 2 0 8 7 7 5 1 2 1 3 7 7 8 1 6 5 2 9 4 2 8 1 5 5
 9 1 1 4 8 0 3 5 0 8 1 4 4 2 4 8 3 3 2 0 9 7 0 8 1 5 3]


In [13]:
from sklearn import metrics
print("Confusion Matrix: ", metrics.confusion_matrix(y_test, y_pred))
print("Accuracy : ", metrics.accuracy_score(y_test,y_pred)*100)
print("Report : ", metrics.classification_report(y_test, y_pred))

Confusion Matrix:  [[32  0  0  0  0  0  0  0  0  0]
 [ 0 17  2  2  7  0  0  0  3  1]
 [ 0  2 26  3  0  0  0  1  1  0]
 [ 0  2  1 32  0  0  0  1  0  1]
 [ 2  2  0  0 30  5  0  0  1  0]
 [ 3  1  0  0  2 36  0  0  0  0]
 [ 0  0  3  0  5  1 30  0  0  0]
 [ 0  0  0  1  0  3  0 20  1  1]
 [ 0  5  7  2  0  0  0  1 20  5]
 [ 0  2  0  4  1  3  0  0  1 28]]
Accuracy :  75.27777777777777
Report :                precision    recall  f1-score   support

           0       0.86      1.00      0.93        32
           1       0.55      0.53      0.54        32
           2       0.67      0.79      0.72        33
           3       0.73      0.86      0.79        37
           4       0.67      0.75      0.71        40
           5       0.75      0.86      0.80        42
           6       1.00      0.77      0.87        39
           7       0.87      0.77      0.82        26
           8       0.74      0.50      0.60        40
           9       0.78      0.72      0.75        39

    accuracy  